# Generated by Django 3.2.15 on 2022-09-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20220928_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
